# Generated by Django 4.1.13 on 2024-03-01 00:48

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afastamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_proex', models.CharField(max_length=50)),
                ('motivo', models.CharField(max_length=500)),
                ('portaria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeExtensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_proex', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('tipo_de_colaboracao', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=100)),
                ('inicio_projeto', models.DateField()),
                ('fim_projeto', models.DateField()),
                ('ano', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeGestaoRepresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('carga_horaria_semanal', models.IntegerField()),
                ('ato_designacao', models.CharField(max_length=100)),
                ('inicio_projeto', models.DateField()),
                ('fim_projeto', models.DateField()),
                ('ano', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeOrientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('ch_semanal_orientacao', models.IntegerField()),
                ('ch_semanal_coorientacao', models.IntegerField()),
                ('ch_semanal_supervisao', models.IntegerField()),
                ('ch_semanal_precep_tutoria', models.IntegerField()),
                ('ch_semanal_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AtividadePedagogicaComplementar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('ch_semanal_grad', models.IntegerField()),
                ('ch_semanal_pos_grad', models.IntegerField()),
                ('ch_semanal_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoDiscente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('numero_documento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BancaExaminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=100)),
                ('titulo_trabalho', models.CharField(max_length=100)),
                ('ies', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('ch_semanal_1', models.IntegerField()),
                ('ch_semanal_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(choices=[('belem', 'Belém'), ('capitao_poco', 'Capitão Poço')], default='belem', max_length=30)),
                ('diretor', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CHSemanalAulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('ch_semanal_grad', models.IntegerField()),
                ('ch_semanal_pos_grad', models.IntegerField()),
                ('ch_semanal_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CHSemanalExtensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CHSemanalPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DistribuicaoCHSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('atividade_didatica', models.IntegerField()),
                ('administracao', models.IntegerField()),
                ('pesquisa', models.IntegerField()),
                ('extensao', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OutrasInformacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_proex', models.CharField(max_length=50)),
                ('decricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressaoPromocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressao_promocao', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoDePesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proped', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('situacao', models.CharField(max_length=100)),
                ('tipo_de_colaboracao', models.CharField(max_length=50)),
                ('ano', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('veiculo_de_publicacao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QualificacaoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_proex', models.CharField(max_length=50)),
                ('atividades', models.CharField(max_length=500)),
                ('portaria_data_realizacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('ano_relatorio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnsinoNaoFormal',
            fields=[
                ('atividadeextensao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.atividadeextensao')),
                ('ch_semanal_1', models.IntegerField()),
                ('ch_semanal_2', models.IntegerField()),
            ],
            bases=('myapp.atividadeextensao',),
        ),
        migrations.CreateModel(
            name='EstagioExtensao',
            fields=[
                ('atividadeextensao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.atividadeextensao')),
                ('ch_semanal', models.IntegerField()),
            ],
            bases=('myapp.atividadeextensao',),
        ),
        migrations.CreateModel(
            name='OutrasAtividadesExtensao',
            fields=[
                ('atividadeextensao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.atividadeextensao')),
                ('ch_semanal_1', models.IntegerField()),
                ('ch_semanal_2', models.IntegerField()),
            ],
            bases=('myapp.atividadeextensao',),
        ),
        migrations.CreateModel(
            name='ProjetoExtensao',
            fields=[
                ('atividadeextensao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.atividadeextensao')),
            ],
            bases=('myapp.atividadeextensao',),
        ),
        migrations.CreateModel(
            name='SupervisaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_semanal_1', models.IntegerField()),
                ('ch_semanal_2', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=30)),
                ('curso', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('atividade_pedagogica_complementar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisao_atividade_pedagogica_complementar', to='myapp.atividadepedagogicacomplementar')),
            ],
        ),
        migrations.CreateModel(
            name='PreceptoriaTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_semanal_1', models.IntegerField()),
                ('ch_semanal_2', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=50)),
                ('atividade_orientacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='preceptoria_atividade_orientacao', to='myapp.atividadeorientacao')),
            ],
        ),
        migrations.CreateModel(
            name='Orientando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_semanal_1', models.IntegerField()),
                ('ch_semanal_2', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=30)),
                ('curso', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('atividade_orientacao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orientando_atividade_orientacao', to='myapp.atividadeorientacao')),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=3)),
                ('campus_nome', models.CharField(max_length=150)),
                ('diretor', models.CharField(max_length=150)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siape', models.CharField(max_length=500)),
                ('classe', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='a', max_length=30)),
                ('vinculo', models.CharField(choices=[('estatuario', 'Estatuário'), ('não selecionado', 'Não selecionado')], max_length=100)),
                ('regime_de_trabalho', models.CharField(choices=[('exclusivo', 'Dedicação Exclusiva'), ('integral', '40h'), ('parcial', '20h')], default='exclusivo', max_length=50)),
                ('titulacao', models.CharField(max_length=100)),
                ('instituto_nome', models.CharField(max_length=150)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docente_campus', to='myapp.campus')),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docente_instituto', to='myapp.instituto')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=3)),
                ('instituto_nome', models.CharField(max_length=150)),
                ('nivel', models.CharField(choices=[('bacharelado', 'Bacharelado'), ('licenciatura', 'Licenciatura'), ('tecnologo', 'Tecnólogo')], default='bacharelado', max_length=30)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curso_campus', to='myapp.campus')),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='curso_instituto', to='myapp.instituto')),
            ],
        ),
        migrations.CreateModel(
            name='CHSemanalEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('total', models.IntegerField()),
                ('item1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ch_semanal_aulas', to='myapp.chsemanalaulas')),
                ('item2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ch_atividade_pedagogica_complementar', to='myapp.atividadepedagogicacomplementar')),
                ('item3', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ch_atividade_orientacao', to='myapp.atividadeorientacao')),
                ('item4', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ch_banca_examinacao', to='myapp.bancaexaminacao')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeLetiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_disciplina', models.CharField(max_length=10)),
                ('nome_disciplina', models.CharField(max_length=70)),
                ('ano', models.CharField(max_length=4)),
                ('semestre', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('qtd_turmas', models.IntegerField()),
                ('carga_horaria_disciplina', models.IntegerField()),
                ('docentes_envolvidos_e_cargas_horarias', models.JSONField()),
                ('carga_horaria_total', models.IntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade_letiva_curso', to='myapp.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=500)),
                ('perfil', models.CharField(choices=[('docente', 'Docente'), ('admin', 'Administrador')], default='docente', max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_docente', to='myapp.docente')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
