# Generated by Django 4.1.13 on 2024-02-27 18:45

from django.db import migrations, models
import django.db.models.deletion
import networkx.classes.function


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDiscente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('numero_documento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CHSemanalAulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('ch_semanal_grad', models.IntegerField()),
                ('ch_semanal_pos_grad', models.IntegerField()),
                ('ch_semanal_total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupervisaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_semanal_1', models.IntegerField()),
                ('ch_semanal_2', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=30)),
                ('curso', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='atividadeorientacao',
            old_name='ano',
            new_name='ch_semanal_coorientacao',
        ),
        migrations.RenameField(
            model_name='atividadeorientacao',
            old_name='carga_horaria',
            new_name='ch_semanal_orientacao',
        ),
        migrations.RenameField(
            model_name='atividadepedagogicacomplementar',
            old_name='carga_horaria_semanal',
            new_name='ch_semanal_grad',
        ),
        migrations.RenameField(
            model_name='bancaexaminacao',
            old_name='ano',
            new_name='ch_semanal_1',
        ),
        migrations.RenameField(
            model_name='bancaexaminacao',
            old_name='semestre',
            new_name='ch_semanal_2',
        ),
        migrations.RenameField(
            model_name='orientando',
            old_name='ano',
            new_name='ch_semanal_1',
        ),
        migrations.RemoveField(
            model_name='atividadeorientacao',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='atividadepedagogicacomplementar',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='atividadepedagogicacomplementar',
            name='carga_horaria_docentes_envolvidos',
        ),
        migrations.RemoveField(
            model_name='atividadepedagogicacomplementar',
            name='docentes_envolvidos',
        ),
        migrations.AddField(
            model_name='atividadeletiva',
            name='carga_horaria_total',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='atividadeletiva',
            name='nivel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeletiva',
            name='numero_turmas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeorientacao',
            name='ch_semanal_precep_tutoria',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeorientacao',
            name='ch_semanal_supervisao',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadeorientacao',
            name='ch_semanal_total',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadepedagogicacomplementar',
            name='ch_semanal_pos_grad',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividadepedagogicacomplementar',
            name='ch_semanal_total',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='ano',
            field=models.DateField(default='20240227'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='siape',
            field=models.CharField(default=222222, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orientando',
            name='ch_semanal_2',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PreceptoriaTutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_semanal_1', models.IntegerField()),
                ('ch_semanal_2', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=50)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.atividadeorientacao')),
            ],
        ),
        migrations.CreateModel(
            name='CHSemanalEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.IntegerField()),
                ('item1', models.ForeignKey(on_delete=networkx.classes.function.to_directed, to='myapp.chsemanalaulas')),
                ('item2', models.ForeignKey(on_delete=networkx.classes.function.to_directed, to='myapp.atividadepedagogicacomplementar')),
                ('item3', models.ForeignKey(on_delete=networkx.classes.function.to_directed, to='myapp.atividadeorientacao')),
                ('item4', models.ForeignKey(on_delete=networkx.classes.function.to_directed, to='myapp.bancaexaminacao')),
            ],
        ),
    ]
