# Generated by Django 4.1.13 on 2024-04-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estagioextensao',
            old_name='insituicao_ou_local',
            new_name='instituicao_ou_local',
        ),
    ]
