# Generated by Django 4.1.13 on 2024-04-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('Docente', 'Docente'), ('Administrador', 'Administrador')], default='Docente', max_length=50),
        ),
    ]
